/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ValidatorRouteImport } from './routes/validator'
import { Route as AdminAdminRouteImport } from './routes/admin/_admin'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as EmployeeEmployeeRouteImport } from './routes/employee/_employee'
import { Route as EmployeeLoginRouteImport } from './routes/employee/login'
import { Route as HistoryIndexRouteImport } from './routes/history.index'
import { Route as HistoryIdRouteImport } from './routes/history.$id'
import { Route as AdminAdminIndexRouteImport } from './routes/admin/_admin.index'
import { Route as AdminAdminEmployeesRouteImport } from './routes/admin/_admin.employees'
import { Route as AdminAdminFilesRouteImport } from './routes/admin/_admin.files'
import { Route as AdminAdminSubmissionsRouteImport } from './routes/admin/_admin.submissions'
import { Route as AdminAdminTasksRouteImport } from './routes/admin/_admin.tasks'
import { Route as AdminAdminValidateRouteImport } from './routes/admin/_admin.validate'
import { Route as EmployeeEmployeeIndexRouteImport } from './routes/employee/_employee.index'
import { Route as EmployeeEmployeeHistoryRouteImport } from './routes/employee/_employee.history'
import { Route as EmployeeEmployeeTasksRouteImport } from './routes/employee/_employee.tasks'
import { Route as EmployeeEmployeeUploadRouteImport } from './routes/employee/_employee.upload'
import { Route as EmployeeEmployeeValidateRouteImport } from './routes/employee/_employee.validate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidatorRoute = ValidatorRouteImport.update({
  id: '/validator',
  path: '/validator',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin/_admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeEmployeeRoute = EmployeeEmployeeRouteImport.update({
  id: '/employee/_employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeLoginRoute = EmployeeLoginRouteImport.update({
  id: '/employee/login',
  path: '/employee/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/history/$id',
  path: '/history/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminEmployeesRoute = AdminAdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminFilesRoute = AdminAdminFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSubmissionsRoute = AdminAdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminTasksRoute = AdminAdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminValidateRoute = AdminAdminValidateRouteImport.update({
  id: '/validate',
  path: '/validate',
  getParentRoute: () => AdminAdminRoute,
} as any)
const EmployeeEmployeeIndexRoute = EmployeeEmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeEmployeeRoute,
} as any)
const EmployeeEmployeeHistoryRoute = EmployeeEmployeeHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => EmployeeEmployeeRoute,
} as any)
const EmployeeEmployeeTasksRoute = EmployeeEmployeeTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => EmployeeEmployeeRoute,
} as any)
const EmployeeEmployeeUploadRoute = EmployeeEmployeeUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => EmployeeEmployeeRoute,
} as any)
const EmployeeEmployeeValidateRoute =
  EmployeeEmployeeValidateRouteImport.update({
    id: '/validate',
    path: '/validate',
    getParentRoute: () => EmployeeEmployeeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/validator': typeof ValidatorRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/employee': typeof EmployeeEmployeeRouteWithChildren
  '/employee/login': typeof EmployeeLoginRoute
  '/history/$id': typeof HistoryIdRoute
  '/history/': typeof HistoryIndexRoute
  '/admin/employees': typeof AdminAdminEmployeesRoute
  '/admin/files': typeof AdminAdminFilesRoute
  '/admin/submissions': typeof AdminAdminSubmissionsRoute
  '/admin/tasks': typeof AdminAdminTasksRoute
  '/admin/validate': typeof AdminAdminValidateRoute
  '/employee/history': typeof EmployeeEmployeeHistoryRoute
  '/employee/tasks': typeof EmployeeEmployeeTasksRoute
  '/employee/upload': typeof EmployeeEmployeeUploadRoute
  '/employee/validate': typeof EmployeeEmployeeValidateRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/employee/': typeof EmployeeEmployeeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/validator': typeof ValidatorRoute
  '/admin/login': typeof AdminLoginRoute
  '/employee/login': typeof EmployeeLoginRoute
  '/history/$id': typeof HistoryIdRoute
  '/history': typeof HistoryIndexRoute
  '/admin/employees': typeof AdminAdminEmployeesRoute
  '/admin/files': typeof AdminAdminFilesRoute
  '/admin/submissions': typeof AdminAdminSubmissionsRoute
  '/admin/tasks': typeof AdminAdminTasksRoute
  '/admin/validate': typeof AdminAdminValidateRoute
  '/employee/history': typeof EmployeeEmployeeHistoryRoute
  '/employee/tasks': typeof EmployeeEmployeeTasksRoute
  '/employee/upload': typeof EmployeeEmployeeUploadRoute
  '/employee/validate': typeof EmployeeEmployeeValidateRoute
  '/admin': typeof AdminAdminIndexRoute
  '/employee': typeof EmployeeEmployeeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/validator': typeof ValidatorRoute
  '/admin/_admin': typeof AdminAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/employee/_employee': typeof EmployeeEmployeeRouteWithChildren
  '/employee/login': typeof EmployeeLoginRoute
  '/history/$id': typeof HistoryIdRoute
  '/history/': typeof HistoryIndexRoute
  '/admin/_admin/employees': typeof AdminAdminEmployeesRoute
  '/admin/_admin/files': typeof AdminAdminFilesRoute
  '/admin/_admin/submissions': typeof AdminAdminSubmissionsRoute
  '/admin/_admin/tasks': typeof AdminAdminTasksRoute
  '/admin/_admin/validate': typeof AdminAdminValidateRoute
  '/employee/_employee/history': typeof EmployeeEmployeeHistoryRoute
  '/employee/_employee/tasks': typeof EmployeeEmployeeTasksRoute
  '/employee/_employee/upload': typeof EmployeeEmployeeUploadRoute
  '/employee/_employee/validate': typeof EmployeeEmployeeValidateRoute
  '/admin/_admin/': typeof AdminAdminIndexRoute
  '/employee/_employee/': typeof EmployeeEmployeeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/validator'
    | '/admin'
    | '/admin/login'
    | '/employee'
    | '/employee/login'
    | '/history/$id'
    | '/history/'
    | '/admin/employees'
    | '/admin/files'
    | '/admin/submissions'
    | '/admin/tasks'
    | '/admin/validate'
    | '/employee/history'
    | '/employee/tasks'
    | '/employee/upload'
    | '/employee/validate'
    | '/admin/'
    | '/employee/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/validator'
    | '/admin/login'
    | '/employee/login'
    | '/history/$id'
    | '/history'
    | '/admin/employees'
    | '/admin/files'
    | '/admin/submissions'
    | '/admin/tasks'
    | '/admin/validate'
    | '/employee/history'
    | '/employee/tasks'
    | '/employee/upload'
    | '/employee/validate'
    | '/admin'
    | '/employee'
  id:
    | '__root__'
    | '/'
    | '/validator'
    | '/admin/_admin'
    | '/admin/login'
    | '/employee/_employee'
    | '/employee/login'
    | '/history/$id'
    | '/history/'
    | '/admin/_admin/employees'
    | '/admin/_admin/files'
    | '/admin/_admin/submissions'
    | '/admin/_admin/tasks'
    | '/admin/_admin/validate'
    | '/employee/_employee/history'
    | '/employee/_employee/tasks'
    | '/employee/_employee/upload'
    | '/employee/_employee/validate'
    | '/admin/_admin/'
    | '/employee/_employee/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ValidatorRoute: typeof ValidatorRoute
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  EmployeeEmployeeRoute: typeof EmployeeEmployeeRouteWithChildren
  EmployeeLoginRoute: typeof EmployeeLoginRoute
  HistoryIdRoute: typeof HistoryIdRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validator': {
      id: '/validator'
      path: '/validator'
      fullPath: '/validator'
      preLoaderRoute: typeof ValidatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin': {
      id: '/admin/_admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/_employee': {
      id: '/employee/_employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/login': {
      id: '/employee/login'
      path: '/employee/login'
      fullPath: '/employee/login'
      preLoaderRoute: typeof EmployeeLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/history/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin/': {
      id: '/admin/_admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/employees': {
      id: '/admin/_admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminAdminEmployeesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/files': {
      id: '/admin/_admin/files'
      path: '/files'
      fullPath: '/admin/files'
      preLoaderRoute: typeof AdminAdminFilesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/submissions': {
      id: '/admin/_admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminAdminSubmissionsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/tasks': {
      id: '/admin/_admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminAdminTasksRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/validate': {
      id: '/admin/_admin/validate'
      path: '/validate'
      fullPath: '/admin/validate'
      preLoaderRoute: typeof AdminAdminValidateRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/employee/_employee/': {
      id: '/employee/_employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeEmployeeIndexRouteImport
      parentRoute: typeof EmployeeEmployeeRoute
    }
    '/employee/_employee/history': {
      id: '/employee/_employee/history'
      path: '/history'
      fullPath: '/employee/history'
      preLoaderRoute: typeof EmployeeEmployeeHistoryRouteImport
      parentRoute: typeof EmployeeEmployeeRoute
    }
    '/employee/_employee/tasks': {
      id: '/employee/_employee/tasks'
      path: '/tasks'
      fullPath: '/employee/tasks'
      preLoaderRoute: typeof EmployeeEmployeeTasksRouteImport
      parentRoute: typeof EmployeeEmployeeRoute
    }
    '/employee/_employee/upload': {
      id: '/employee/_employee/upload'
      path: '/upload'
      fullPath: '/employee/upload'
      preLoaderRoute: typeof EmployeeEmployeeUploadRouteImport
      parentRoute: typeof EmployeeEmployeeRoute
    }
    '/employee/_employee/validate': {
      id: '/employee/_employee/validate'
      path: '/validate'
      fullPath: '/employee/validate'
      preLoaderRoute: typeof EmployeeEmployeeValidateRouteImport
      parentRoute: typeof EmployeeEmployeeRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminEmployeesRoute: typeof AdminAdminEmployeesRoute
  AdminAdminFilesRoute: typeof AdminAdminFilesRoute
  AdminAdminSubmissionsRoute: typeof AdminAdminSubmissionsRoute
  AdminAdminTasksRoute: typeof AdminAdminTasksRoute
  AdminAdminValidateRoute: typeof AdminAdminValidateRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminEmployeesRoute: AdminAdminEmployeesRoute,
  AdminAdminFilesRoute: AdminAdminFilesRoute,
  AdminAdminSubmissionsRoute: AdminAdminSubmissionsRoute,
  AdminAdminTasksRoute: AdminAdminTasksRoute,
  AdminAdminValidateRoute: AdminAdminValidateRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface EmployeeEmployeeRouteChildren {
  EmployeeEmployeeHistoryRoute: typeof EmployeeEmployeeHistoryRoute
  EmployeeEmployeeTasksRoute: typeof EmployeeEmployeeTasksRoute
  EmployeeEmployeeUploadRoute: typeof EmployeeEmployeeUploadRoute
  EmployeeEmployeeValidateRoute: typeof EmployeeEmployeeValidateRoute
  EmployeeEmployeeIndexRoute: typeof EmployeeEmployeeIndexRoute
}

const EmployeeEmployeeRouteChildren: EmployeeEmployeeRouteChildren = {
  EmployeeEmployeeHistoryRoute: EmployeeEmployeeHistoryRoute,
  EmployeeEmployeeTasksRoute: EmployeeEmployeeTasksRoute,
  EmployeeEmployeeUploadRoute: EmployeeEmployeeUploadRoute,
  EmployeeEmployeeValidateRoute: EmployeeEmployeeValidateRoute,
  EmployeeEmployeeIndexRoute: EmployeeEmployeeIndexRoute,
}

const EmployeeEmployeeRouteWithChildren =
  EmployeeEmployeeRoute._addFileChildren(EmployeeEmployeeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ValidatorRoute: ValidatorRoute,
  AdminAdminRoute: AdminAdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  EmployeeEmployeeRoute: EmployeeEmployeeRouteWithChildren,
  EmployeeLoginRoute: EmployeeLoginRoute,
  HistoryIdRoute: HistoryIdRoute,
  HistoryIndexRoute: HistoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
